### PR TITLE
Feature/support generics

### PR DESCRIPTION
**Pull request by mrpmorris**
This pull request splits the MethodInfo caching used by DotNetDispatcher into two; one for calling static methods and one for calling instance methods.

Method identifiers on static methods must be unique per assembly, whereas for instance methods they only need to be unique for the instance's class hierarchy.

Generics are now supported, but only when invoking instance methods and only if there are no open generics. 

JSInvokable now no longer has a parameterless constructor so that the specifying of the method identifier is always explicit as per @SteveSandersonMS's suggestion on [Twitter](https://twitter.com/stevensanderson/status/1055432525344993280).

Addresses issues 

- https://github.com/aspnet/Blazor/issues/1557
- https://github.com/aspnet/Blazor/issues/1558

### CODE REVIEW

**Comment by mrpmorris** [comment]
@danroth27 @SteveSandersonMS This PR has been done for a while as per direction given to me by Steve, wondering if it has been forgotten?

**Comment by SteveSandersonMS** [comment]
@mrpmorris Sorry for the slow response. It's on my backlog to review soon.

**Comment by mrpmorris** [comment]
Thanks for the update @SteveSandersonMS - Don't mean to hassle, just want to make sure that if it doesn't get in it's because you didn't like it rather than because it got lost 👍

**Comment by aspnet-hello** [comment]
We're closing this item because this project has moved to another repo.

Please go to https://github.com/aspnet/Extensions/tree/master/src/JSInterop to see the latest JSInterop code base and to file issues.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.

**Pull request closed without merging**
